# Generated by Django 5.0.6 on 2026-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="description",
            new_name="summary",
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("treatment", "Treatment"),
                    ("diagnosis", "Diagnosis"),
                    ("nutrition", "Nutrition"),
                    ("rehab", "Rehab"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="articles_pdfs/"),
        ),
    ]
