# Generated by Django 5.2.8 on 2026-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
