# Generated by Django 5.2.8 on 2026-01-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_verification_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
