# Generated by Django 5.0.6 on 2026-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
