# Generated by Django 5.0.6 on 2026-01-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_reminder_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.appointmentslot",
            ),
        ),
    ]
