# Generated by Django 5.0.6 on 2026-01-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointment_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
